import { NotFoundError, ValidationFailureError } from "../../errors/app-error";
import type { CaseAuthorizationService } from "../../auth/case-authorization-service";
import type { RepositoryContext, TransactionCoordinator } from "../../repositories/repository-context";
import type { Actor, AddressIntelligenceObservationRecord, AttributionEvidenceInput, AttributionReviewInput, EntityType, ServiceAddressAssessmentInput, VaspCandidateInput } from "../../repositories/types";
import { conflictsFor } from "./address-intelligence-service";
import { ATTRIBUTION_SCORING_METHOD, ATTRIBUTION_SCORING_VERSION, fuseAttributionEvidence } from "./attribution-evidence-fusion-service";

const serviceTypes = new Set<EntityType>(["EXCHANGE", "VASP", "CUSTODIAL_SERVICE"]);
export class ServiceAddressAssessmentService {
  assess(chain: string, address: string, observations: AddressIntelligenceObservationRecord[], relationshipCount: number): ServiceAddressAssessmentInput {
    const conflict = conflictsFor(observations).length > 0; const direct = observations.filter((value) => serviceTypes.has(value.entityType)); const freshest = direct.some((value) => value.freshnessStatus === "FRESH"); const stale = direct.some((value) => value.freshnessStatus === "STALE" || value.freshnessStatus === "EXPIRED");
    const directScore = direct.length ? 60 : 0; const behaviorScore = relationshipCount >= 3 ? 10 : 0; const score = Math.max(0, directScore + behaviorScore - (stale ? 15 : 0) - (conflict ? 35 : 0));
    const first = direct[0]; const classification = !first ? "UNKNOWN" : first.entityType === "VASP" ? "VASP" : first.entityType === "CUSTODIAL_SERVICE" ? "CUSTODIAL_WALLET" : "EXCHANGE_ENTITY";
    return { chain, address, classification, confidenceLevel: conflict || score < 30 ? "UNKNOWN" : score >= 70 && freshest ? "LIKELY" : "POSSIBLE", numericScore: score, status: conflict ? "CONFLICTING_EVIDENCE" : direct.length ? "PENDING_REVIEW" : "INSUFFICIENT_EVIDENCE", signals: [{ directServiceLabelCount: direct.length, graphRelationshipCount: relationshipCount, stale, conflict, caveat: "service_or_deposit_address_is_not_a_person_identity" }] };
  }
}
export class VaspCandidateService {
  private readonly assessments = new ServiceAddressAssessmentService();
  constructor(private readonly repositories: RepositoryContext, private readonly transactions: TransactionCoordinator, private readonly authorization: CaseAuthorizationService) {}
  async analyze(actor: Actor, investigationId: string, maxAddresses = 100, maxCandidates = 50, requestId?: string) {
    const investigation = await this.repositories.investigations.findAccessibleById(actor, investigationId);
    if (!investigation) throw new NotFoundError("Investigation not found.");
    await this.authorization.requireCaseAccess(actor, investigation.caseId, "VASP_ANALYZE", requestId);
    if (!investigation.chain) throw new ValidationFailureError("Investigation chain is required for VASP analysis.");
    if (![maxAddresses, maxCandidates].every((value) => Number.isInteger(value) && value >= 1 && value <= 250)) throw new ValidationFailureError("Analysis bounds must be integers between 1 and 250.");
    const [observations, relationships, clusters] = await Promise.all([this.repositories.intelligence.listObservationsForInvestigation(investigation.caseId, investigationId, investigation.chain, maxAddresses + 1), this.repositories.graph.listByCaseAndChain(investigation.caseId, investigation.chain), this.repositories.intelligence.listClusters(investigation.caseId, investigationId, 100)]);
    const addresses = [...new Set(observations.map((value) => value.address.toLowerCase()))].sort().slice(0, maxAddresses); const candidates = [] as Awaited<ReturnType<RepositoryContext["intelligence"]["upsertVaspCandidate"]>>[];
    await this.transactions.transaction(async (repositories) => { for (const normalizedAddress of addresses) { if (candidates.length >= maxCandidates) break; const addressObservations = observations.filter((value) => value.address.toLowerCase() === normalizedAddress); const service = this.assessments.assess(investigation.chain!, addressObservations[0].address, addressObservations, relationships.filter((edge) => edge.fromAddress.toLowerCase() === normalizedAddress || edge.toAddress.toLowerCase() === normalizedAddress).length); await repositories.intelligence.upsertServiceAssessment(investigation.caseId, investigationId, service); const entities = [...new Set(addressObservations.filter((value) => serviceTypes.has(value.entityType)).map((value) => value.entityName ?? value.label).filter((value): value is string => Boolean(value)))].sort(); for (const entityName of entities) { if (candidates.length >= maxCandidates) break; const entityObservations = addressObservations.filter((value) => (value.entityName ?? value.label) === entityName); const evidence = candidateEvidence(investigation.chain!, addressObservations[0].address, entityObservations, relationships.length, clusters.some((cluster) => cluster.members.some((member) => member.address.toLowerCase() === normalizedAddress))); const fused = fuseAttributionEvidence(evidence); const input: VaspCandidateInput = { chain: investigation.chain!, address: addressObservations[0].address, entityName, entityType: entityObservations[0].entityType, confidenceLevel: fused.confidenceLevel, numericScore: fused.numericScore, status: fused.contradictions.length ? "CONFLICTING_EVIDENCE" : fused.confidenceLevel === "UNKNOWN" ? "INSUFFICIENT_EVIDENCE" : "PENDING_REVIEW", reason: "Deterministic evidence fusion produces an investigative service/entity candidate only; it does not identify a person or customer.", contradictions: fused.contradictions, method: ATTRIBUTION_SCORING_METHOD, methodVersion: ATTRIBUTION_SCORING_VERSION, evidence }; candidates.push(await repositories.intelligence.upsertVaspCandidate(investigation.caseId, investigationId, input)); } } await repositories.audit.append({ caseId: investigation.caseId, actorId: actor.id, action: "VASP_CANDIDATE_ANALYSIS_EXECUTED", resourceType: "investigation", resourceId: investigationId, requestId: requestId ?? null, result: "SUCCESS", metadata: { observationCount: observations.length, candidateCount: candidates.length, maxAddresses, maxCandidates, truncated: observations.length > maxAddresses || candidates.length >= maxCandidates, method: ATTRIBUTION_SCORING_METHOD, methodVersion: ATTRIBUTION_SCORING_VERSION } }); });
    return { status: candidates.length ? "OK" : "INSUFFICIENT_EVIDENCE", candidates, truncated: observations.length > maxAddresses || candidates.length >= maxCandidates };
  }
  async list(actor: Actor, investigationId: string, limit = 50, requestId?: string) { const investigation = await this.repositories.investigations.findAccessibleById(actor, investigationId); if (!investigation) throw new NotFoundError("Investigation not found."); await this.authorization.requireCaseAccess(actor, investigation.caseId, "INTELLIGENCE_READ", requestId); return this.repositories.intelligence.listVaspCandidates(investigation.caseId, investigationId, Math.min(Math.max(limit, 1), 100)); }
  async review(actor: Actor, investigationId: string, candidateId: string, input: AttributionReviewInput, requestId?: string) {
    const investigation = await this.repositories.investigations.findAccessibleById(actor, investigationId); if (!investigation) throw new NotFoundError("Investigation not found.");
    await this.authorization.requireCaseAccess(actor, investigation.caseId, "VASP_REVIEW", requestId);
    const candidate = await this.repositories.intelligence.findVaspCandidate(investigation.caseId, investigationId, candidateId); if (!candidate) throw new NotFoundError("VASP candidate not found.");
    if (input.decision === "CONFIRMED" && !canConfirmCandidate(candidate)) throw new ValidationFailureError("Confirmation requires an uncontested LIKELY candidate with at least two sourced supporting observations.");
    return this.transactions.transaction(async (repositories) => { const review = await repositories.intelligence.appendReview(investigation.caseId, investigationId, candidateId, actor.id, input); await repositories.audit.append({ caseId: investigation.caseId, actorId: actor.id, action: "VASP_CANDIDATE_REVIEWED", resourceType: "vasp_candidate", resourceId: candidateId, requestId: requestId ?? null, result: "SUCCESS", metadata: { decision: input.decision, candidateConfidenceLevel: candidate.confidenceLevel, evidenceCount: candidate.evidence.length, contradictionCount: candidate.contradictions.length } }); return review; });
  }
}
export function canConfirmCandidate(candidate: { confidenceLevel: string; status: string; contradictions: Record<string, unknown>[]; evidence: Array<{ polarity: string; source: string | null }> }) { return candidate.confidenceLevel === "LIKELY" && candidate.status === "PENDING_REVIEW" && candidate.contradictions.length === 0 && candidate.evidence.filter((item) => item.polarity === "SUPPORTING" && item.source).length >= 2; }
function candidateEvidence(chain: string, address: string, observations: AddressIntelligenceObservationRecord[], graphRelationshipCount: number, clusterSupport: boolean): AttributionEvidenceInput[] { const evidence: AttributionEvidenceInput[] = []; for (const observation of observations) { evidence.push({ category: "ADDRESS_INTELLIGENCE", evidenceType: "PUBLIC_SERVICE_LABEL", subjectType: "address", subjectId: `${chain}:${address}`, polarity: "SUPPORTING", contribution: observation.freshnessStatus === "FRESH" ? 45 : 30, source: observation.source, sourceReference: observation.sourceReference, sourceUrl: observation.sourceUrl, retrievedAt: observation.retrievedAt, method: "approved-source-observation", methodVersion: "1.0.0", rawReference: observation.rawReference, details: { entityType: observation.entityType, freshnessStatus: observation.freshnessStatus, confidence: observation.confidence } }); if (observation.freshnessStatus === "STALE" || observation.freshnessStatus === "EXPIRED") evidence.push({ category: "SOURCE_QUALITY", evidenceType: "STALE_LABEL", subjectType: "address", subjectId: `${chain}:${address}`, polarity: "NEGATIVE", contribution: -15, source: observation.source, sourceReference: observation.sourceReference, sourceUrl: observation.sourceUrl, retrievedAt: observation.retrievedAt, method: "source-freshness", methodVersion: "1.0.0", rawReference: observation.rawReference, details: { freshnessStatus: observation.freshnessStatus } }); }
  if (graphRelationshipCount) evidence.push({ category: "GRAPH_EVIDENCE", evidenceType: "STORED_GRAPH_PROXIMITY", subjectType: "address", subjectId: `${chain}:${address}`, polarity: "SUPPORTING", contribution: Math.min(20, graphRelationshipCount * 5), source: null, sourceReference: null, sourceUrl: null, retrievedAt: null, method: "phase4-stored-relationship-count", methodVersion: "1.0.0", rawReference: null, details: { graphRelationshipCount } });
  if (new Set(observations.map((value) => value.source)).size >= 2) evidence.push({ category: "SOURCE_AGREEMENT", evidenceType: "INDEPENDENT_SOURCE_AGREEMENT", subjectType: "address", subjectId: `${chain}:${address}`, polarity: "SUPPORTING", contribution: 15, source: null, sourceReference: null, sourceUrl: null, retrievedAt: null, method: "distinct-source-count", methodVersion: "1.0.0", rawReference: null, details: { sourceCount: new Set(observations.map((value) => value.source)).size } });
  if (clusterSupport) evidence.push({ category: "CLUSTER_INFERENCE", evidenceType: "BITCOIN_CLUSTER_SUPPORT", subjectType: "address", subjectId: `${chain}:${address}`, polarity: "SUPPORTING", contribution: 5, source: null, sourceReference: null, sourceUrl: null, retrievedAt: null, method: "review-required-cluster-inference", methodVersion: "1.0.0", rawReference: null, details: { caveat: "inference_not_fact" } });
  if (conflictsFor(observations).length) evidence.push({ category: "SOURCE_QUALITY", evidenceType: "CONFLICTING_LABELS", subjectType: "address", subjectId: `${chain}:${address}`, polarity: "CONTRADICTORY", contribution: -35, source: null, sourceReference: null, sourceUrl: null, retrievedAt: null, method: "label-conflict-detection", methodVersion: "1.0.0", rawReference: null, details: { entities: conflictsFor(observations)[0].entityNames } }); return evidence; }
