export type PermissionCode =
  | "CASE_CREATE" | "CASE_READ" | "CASE_UPDATE" | "CASE_CLOSE" | "CASE_ASSIGN"
  | "INVESTIGATION_CREATE" | "INVESTIGATION_READ" | "INVESTIGATION_EXECUTE"
  | "EVIDENCE_CREATE" | "EVIDENCE_READ" | "EVIDENCE_EXPORT"
  | "REPORT_READ" | "REPORT_CREATE" | "REPORT_EXPORT" | "AUDIT_READ" | "USER_MANAGE" | "ROLE_MANAGE"
  | "INTELLIGENCE_READ" | "INTELLIGENCE_EXECUTE" | "CLUSTER_ANALYZE" | "VASP_ANALYZE" | "VASP_REVIEW" | "EVIDENCE_REVIEW"
  | "RISK_ANALYZE" | "RISK_READ" | "GRAPH_FEATURES" | "DEFI_ANALYZE"
  | "REPORT_GENERATE" | "REPORT_EXPORT" | "AUDIT_EXPORT"
  | "COLLECTION_BNB" | "COLLECTION_POLYGON" | "COLLECTION_SOLANA";

export type Actor = { id: string; username: string; roles: string[]; permissions: PermissionCode[] };
export type CaseStatus = "OPEN" | "IN_PROGRESS" | "ON_HOLD" | "CLOSED" | "ARCHIVED";
export type InvestigationStatus = "CREATED" | "AUTHORIZED" | "RUNNING" | "COMPLETED" | "PARTIAL" | "FAILED" | "CANCELLED";
export type CaseRecord = { id: string; caseNumber: string; title: string; description: string; fraudType: string; reportedAmount: string; status: CaseStatus; priority: string; investigationAuthorizationStatus: "PENDING" | "APPROVED" | "REJECTED"; createdBy: string | null; assignedTo: string | null; closedAt: string | null; createdAt: string; updatedAt: string };
export type InvestigationRecord = { id: string; caseId: string; status: InvestigationStatus; chain: string | null; walletAddress: string | null; investigationDepth: number; startTime: string | null; endTime: string | null; createdBy: string | null; createdAt: string; updatedAt: string };
export type WalletSubjectRecord = { id: string; caseId: string; investigationId: string; chain: string; walletAddress: string; label: "REPORTED" | "SUSPECT" | "SUBJECT" | "OBSERVED" | "UNKNOWN"; createdAt: string };
export type EvidenceRecord = { id: string; caseId: string | null; investigationId: string | null; subjectType: string; subjectId: string; evidenceType: string; sourceType: string; provider: string | null; sourceReference: string | null; sourceUrl: string | null; observedAt: string | null; collectedAt: string | null; method: string | null; confidence: number | null; rawReference: string | null; contentHash: string | null; description: string | null; createdBy: string | null; createdAt: string };
export type AuditEventRecord = { id: string; caseId: string | null; actorId: string | null; action: string; resourceType: string; resourceId: string | null; requestId: string | null; result: "SUCCESS" | "DENIED" | "FAILURE"; metadata: Record<string, unknown>; createdAt: string };
export type GraphRelationshipType = "TRANSFER" | "TOKEN_TRANSFER" | "INTERNAL_TRANSFER" | "CONTRACT_INTERACTION" | "UTXO_SPEND";
export type GraphRelationshipRecord = { id: string; caseId: string; chain: string; transactionHash: string; fromAddress: string; toAddress: string; relationshipType: GraphRelationshipType; asset: string; amount: string; tokenContract: string | null; blockNumber: string | null; timestamp: string | null; executionStatus: string | null; derivationSourceType: "API" | "INFERENCE"; provider: string | null; sourceReference: string | null; rawReference: string | null; retrievedAt: string | null; method: string; createdAt: string };
export type GraphRelationshipInput = Omit<GraphRelationshipRecord, "id" | "caseId" | "createdAt">;
export type EntityType = "EXCHANGE" | "VASP" | "CUSTODIAL_SERVICE" | "DEX" | "BRIDGE" | "MIXER" | "MINING_POOL" | "DEFI" | "SCAM" | "PHISHING" | "SANCTIONED_ENTITY" | "OTHER" | "UNKNOWN";
export type IntelligenceStatus = "UNKNOWN" | "ACTIVE" | "STALE" | "CONFLICTING" | "REVIEW_REQUIRED";
export type FreshnessStatus = "FRESH" | "STALE" | "EXPIRED" | "UNKNOWN";
export type ConfidenceLevel = "UNKNOWN" | "POSSIBLE" | "LIKELY" | "CONFIRMED";
export type AddressIntelligenceObservationRecord = { id: string; caseId: string; investigationId: string; chain: string; address: string; label: string | null; entityName: string | null; entityType: EntityType; source: string; sourceReference: string | null; sourceUrl: string | null; datasetName: string | null; datasetVersion: string | null; license: string | null; retrievedAt: string; lastVerified: string | null; freshnessStatus: FreshnessStatus; confidence: number; status: IntelligenceStatus; rawReference: string | null; rawData: Record<string, unknown> | null; createdAt: string; updatedAt: string };
export type AddressIntelligenceObservationInput = Omit<AddressIntelligenceObservationRecord, "id" | "caseId" | "investigationId" | "createdAt" | "updatedAt">;
export type ClusterMember = { address: string; membershipType: "COMMON_INPUT" | "POSSIBLE_CHANGE" | "CONSOLIDATION"; evidence: Record<string, unknown>[] };
export type ClusterInferenceRecord = { id: string; caseId: string; investigationId: string; clusterKey: string; chain: "BITCOIN"; method: string; methodVersion: string; confidenceLevel: Exclude<ConfidenceLevel, "CONFIRMED">; numericScore: number; reviewStatus: "PENDING_REVIEW" | "ACCEPTED" | "REJECTED"; ambiguityReason: string | null; evidence: Record<string, unknown>[]; members: ClusterMember[]; createdAt: string; updatedAt: string };
export type ClusterInferenceInput = Omit<ClusterInferenceRecord, "id" | "caseId" | "investigationId" | "createdAt" | "updatedAt">;
export type ServiceAddressAssessmentRecord = { id: string; caseId: string; investigationId: string; chain: string; address: string; classification: "EXCHANGE_ENTITY" | "EXCHANGE_HOT_WALLET" | "EXCHANGE_DEPOSIT_ADDRESS" | "CUSTODIAL_WALLET" | "VASP" | "OTHER_SERVICE" | "UNKNOWN"; confidenceLevel: Exclude<ConfidenceLevel, "CONFIRMED">; numericScore: number; status: "PENDING_REVIEW" | "CONFLICTING_EVIDENCE" | "INSUFFICIENT_EVIDENCE"; signals: Record<string, unknown>[]; createdAt: string; updatedAt: string };
export type ServiceAddressAssessmentInput = Omit<ServiceAddressAssessmentRecord, "id" | "caseId" | "investigationId" | "createdAt" | "updatedAt">;
export type AttributionEvidenceInput = { category: "DIRECT_BLOCKCHAIN_FACT" | "GRAPH_EVIDENCE" | "ADDRESS_INTELLIGENCE" | "CLUSTER_INFERENCE" | "ABUSE_INTELLIGENCE" | "SOURCE_AGREEMENT" | "SOURCE_QUALITY"; evidenceType: string; subjectType: string; subjectId: string; polarity: "SUPPORTING" | "NEGATIVE" | "CONTRADICTORY"; contribution: number; source: string | null; sourceReference: string | null; sourceUrl: string | null; retrievedAt: string | null; method: string; methodVersion: string; rawReference: string | null; details: Record<string, unknown> };
export type VaspCandidateRecord = { id: string; caseId: string; investigationId: string; chain: string; address: string; entityName: string | null; entityType: EntityType; confidenceLevel: ConfidenceLevel; numericScore: number; status: "PENDING_REVIEW" | "CONFLICTING_EVIDENCE" | "INSUFFICIENT_EVIDENCE" | "CONFIRMED_BY_REVIEW"; reason: string; contradictions: Record<string, unknown>[]; method: string; methodVersion: string; evidence: AttributionEvidenceInput[]; createdAt: string; updatedAt: string };
export type VaspCandidateInput = Omit<VaspCandidateRecord, "id" | "caseId" | "investigationId" | "createdAt" | "updatedAt">;
export type AttributionReviewDecision = "ACCEPTED" | "REJECTED" | "CONFIRMED";
export type AttributionReviewRecord = { id: string; caseId: string; investigationId: string; candidateId: string; reviewerId: string; decision: AttributionReviewDecision; rationale: string | null; createdAt: string };
export type AttributionReviewInput = { decision: AttributionReviewDecision; rationale: string | null };
export type BitcoinTransactionRecord = { transactionHash: string; inputs: Array<{ address: string | null; value: string | null }>; outputs: Array<{ address: string | null; value: string }>; };
export type RiskIndicatorPersistenceInput = { indicatorType: string; severity: "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; scoreContribution: number; confidence: "LOW" | "MEDIUM" | "HIGH"; description: string; explanation: string; ruleVersion: string; evidence: Array<{ evidenceType: string; subjectType: string; subjectId: string; value?: string; source?: string; sourceReference?: string; method: string; methodVersion: string }>; observedAt?: string };
export type RiskAnalysisRunRecord = { id: string; caseId: string; investigationId: string; chain: string; address: string; method: string; methodVersion: string; status: "COMPLETED" | "FAILED" | "PARTIAL"; indicatorCount: number; totalRiskScore: number | null; createdAt: string };
export type PersistedRiskIndicator = { id: string; runId: string; caseId: string; investigationId: string; chain: string; address: string | null; indicatorType: string; severity: string; scoreContribution: number; confidence: string; description: string; explanation: string; method: string; methodVersion: string; observedAt: string | null; createdAt: string };
export type GraphFeaturePersistenceInput = { chain: string; address: string; featureType: string; value: number; method: string; methodVersion: string; scopeDescription: string; computedAt: string };
export type PersistedGraphFeature = GraphFeaturePersistenceInput & { id: string; caseId: string; investigationId: string };
export type CommunityPersistenceInput = { communityKey: string; members: string[]; memberCount: number; edgeCount: number; chains: string[]; confidence: "STRUCTURAL" | "INFERRED"; explanation: string; method: string; methodVersion: string };
export type CommunityRunRecord = { id: string; caseId: string; investigationId: string; chain: string; totalNodes: number; totalEdges: number; communityCount: number; createdAt: string };
export type DeFiInteractionPersistenceInput = { chain: string; transactionHash: string; protocolAddress: string; protocolName?: string; interactionType: "SWAP" | "LIQUIDITY_ADD" | "LIQUIDITY_REMOVE" | "BORROW" | "REPAY" | "FLASH_LOAN" | "BRIDGE" | "OTHER"; tokenIn?: string; amountIn?: string; tokenOut?: string; amountOut?: string; routerAddress?: string; method: string; methodVersion: string };
export type MevCandidatePersistenceInput = { chain: string; mevType: "SANDWICH" | "ARBITRAGE" | "LIQUIDATION" | "OTHER"; confidenceLevel: "CANDIDATE" | "LIKELY" | "REVIEW_REQUIRED"; frontRunHash?: string; victimHash?: string; backRunHash?: string; poolAddress?: string; profitEstimate?: string; evidence: unknown[]; method: string; methodVersion: string };
export type ForensicReportPersistenceInput = { title: string; reportType: "INVESTIGATION_SUMMARY" | "RISK_ASSESSMENT" | "GRAPH_ANALYSIS" | "FULL_FORENSIC"; content: Record<string, unknown>; methodVersions: Record<string, string> };
export type ForensicReportRecord = ForensicReportPersistenceInput & { id: string; caseId: string; investigationId: string | null; generatedBy: string | null; createdAt: string };
