import { index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { cases } from "./cases";

export const wallets = pgTable("wallets", {
  id: uuid("id").defaultRandom().primaryKey(), caseId: uuid("case_id").references(() => cases.id), chain: text("chain").notNull(), address: text("address").notNull(),
  sourceType: text("source_type").notNull(), provider: text("provider"), sourceReference: text("source_reference"), rawReference: text("raw_reference"), rawData: jsonb("raw_data"), retrievedAt: timestamp("retrieved_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("wallets_case_id_idx").on(table.caseId), index("wallets_chain_address_idx").on(table.chain, table.address), uniqueIndex("wallets_case_chain_address_unique").on(table.caseId, table.chain, table.address)]);

export const blockchainTransactions = pgTable("blockchain_transactions", {
  id: uuid("id").defaultRandom().primaryKey(), caseId: uuid("case_id").references(() => cases.id), walletId: uuid("wallet_id").references(() => wallets.id), chain: text("chain").notNull(), transactionHash: text("transaction_hash").notNull(), blockNumber: numeric("block_number"), blockHash: text("block_hash"), blockTimestamp: timestamp("block_timestamp", { withTimezone: true }), confirmations: integer("confirmations"), sourceType: text("source_type").notNull(), provider: text("provider"), sourceReference: text("source_reference"), rawReference: text("raw_reference"), rawData: jsonb("raw_data"), retrievedAt: timestamp("retrieved_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("transactions_chain_hash_idx").on(table.chain, table.transactionHash), index("transactions_block_number_idx").on(table.chain, table.blockNumber)]);

export const transactionInputs = pgTable("transaction_inputs", { id: uuid("id").defaultRandom().primaryKey(), transactionId: uuid("transaction_id").notNull().references(() => blockchainTransactions.id, { onDelete: "cascade" }), inputIndex: integer("input_index").notNull(), address: text("address"), valueNumeric: numeric("value_numeric"), previousTransactionHash: text("previous_transaction_hash"), previousOutputIndex: integer("previous_output_index"), script: text("script"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("transaction_inputs_transaction_index_unique").on(table.transactionId, table.inputIndex)]);
export const transactionOutputs = pgTable("transaction_outputs", { id: uuid("id").defaultRandom().primaryKey(), transactionId: uuid("transaction_id").notNull().references(() => blockchainTransactions.id, { onDelete: "cascade" }), outputIndex: integer("output_index").notNull(), address: text("address"), valueNumeric: numeric("value_numeric").notNull(), script: text("script"), spendingTransactionHash: text("spending_transaction_hash"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("transaction_outputs_transaction_index_unique").on(table.transactionId, table.outputIndex)]);
